### ISSUE TITLE
convert Lua model to pytorch model

### ISSUE THREAD

**Issue by rafikg** [jpuigcerver/PyLaia#13]
Hello @jpuigcerver,
just to let you now that I have converted your pretrained Lua model to pytorch model and It is working fine just to do inference....

**Comment by jpuigcerver** [comment]
Could you report the CER/WER on IAM?

**Comment by jpuigcerver** [comment]
@Gouiaa perhaps you put publish somewhere the code to convert the model, as an illustration for other users. That would be very much appreciated.
