### ISSUE TITLE
Error in run_epoch

### ISSUE THREAD

**Issue by karna2605** [jpuigcerver/PyLaia#17]
Hi,
First, I would like to great you for this awesome work. It is very well coded!
Now I think there is an error at this line: https://github.com/jpuigcerver/PyLaia/blob/7ee6b8c9371b5d8edd19f720a9dc8b3aabb1a704/laia/engine/engine.py#L225

There should be an "else" and the two next lines should be unindented: if not, we go in a dead loop in my mind.

Thank you for your answer.

**Comment by carmocca** [comment]
Hi, thanks!

I don't see the problem. This is a [`for..else`](http://book.pythontips.com/en/latest/for_-_else.html) loop meaning that the code inside the `else` block gets executed only when the loop has finished and a `break` statement has not been executed.

The purpose of this is that the number of epochs increases only when all iterations have been completed. Some experiments have too much data and can't be run for a full epoch.

Does this solve your issue?

**Comment by karna2605** [comment]
Hi, thank you for your quick answer!
I see your point and indeed I changed a bit your code to test some other things and it came up with a dead loop.
Sorry for the disturbance.
Great job again !
