### ISSUE TITLE
How to do Language Model based decoding

### ISSUE THREAD

**Issue by dutta1kartik3** [jpuigcerver/PyLaia#19]
Hi,
Would appreciate if you could provide instructions on how to use language model with the IAM example, like it was shown in Laia/

**Comment by jpuigcerver** [comment]
Hi,

In egs/iam/utils there are scripts to prepare the character LMs and the necessary FSTs to use them. You'll need to create a script similar to egs/iam/steps/decode_lm.sh but that uses these scripts instead. 

I don't have the time now to write a complete tutorial on how to do this, but please, don't hesitate to ask any other concrete question that you may have.

**Comment by jpuigcerver** [comment]
Closing this issue. Please, re-open it if you have more questions.
