### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by carmocca** [jpuigcerver/PyLaia#21]
Hey @jpuigcerver,

I was thinking we could do some branch cleanup. I'm asking you first in case you have local changes which have not been pushed. We could also have master be called master again.

I'm talking about deleting egs, icfhr2014kws, kws_gw, refactor_crnn_model, and refactor_kws_egs since they don't have any changes. Also possibly PyTorch-0.3.1

**Comment by carmocca** [comment]
Done.

**Comment by carmocca** [comment]
@jpuigcerver Can you make master default again? Only the repository owner can.

It is in https://github.com/jpuigcerver/PyLaia/settings/branches

**Comment by jpuigcerver** [comment]
Done!
