### ISSUE TITLE
Issues using images with more than one Channel

### ISSUE THREAD

**Issue by vbosch** [jpuigcerver/PyLaia#24]
At the moment I am trying to use PyLaia with images that have more than one channel. 

Unfortunately the training script pylaia-htr-train-ctc loads both training and validation images with image_channels=1 ( for example in line 168 of this script). If I leave this value at 1 although the model is set to have 3 channels and the images used have 3 channels I get the following exception: 

Exception "AssertionError('Input image depth (1) does not match the expected (3)')"

If I set the value to 3 I get errors from the padding_collater.py: 

 File "/usr/local/lib/python3.7/dist-packages/laia-0.1.0-py3.7.egg/laia/data/padding_collater.py", line 31, in _get_max_size_and_check_batch_tensor
    assert maxv == expected_shape[d] and minv == expected_shape[d]

Is there a way to workaround this issue ?

**Comment by jpuigcerver** [comment]
You need to change both:
- image_channels=1 -> image_channels=3
- transforms.vision.Convert("L") -> transforms.vision.Convert("RGB")

**Comment by vbosch** [comment]
Hi Joan,

Thanks for your reply, we also managed to end up with the same solution over here, but I was wondering if maybe this could be an input parameter for the training script. 

In any case as the base issue is resolved I will close this.
