### ISSUE TITLE
Non-editable installation is broken

### ISSUE THREAD

**Issue by lexming** [jpuigcerver/PyLaia#33]
The release package of PyLaia v1.0.0 cannot be installed as a regular non-editable module. There are two main issues that render the resulting installation in a broken state:
* Folders `laia/scripts` and `laia/models` lack the needed `__init__.py` to be recognized as Python modules and, hence, they are ignored and not installed by `pip`.
* The method `get_installed_versions()` relies on the presence of `requirements.txt`. `pip` will not install that file and the method will fail.

Installing PyLaia as an editable module is not an option for us as we want to make the software available to multiple users.

**Comment by carmocca** [comment]
Nice catch! 

Can you open a PR fixing these issues?

**Comment by lexming** [comment]
Sorry, but it is not for me to make those changes. You, as dev of the project, should first decide if you really want to print those log messages with the version of those packages and, if so, decide the best approach to not rely on `requirements.txt`. I would also suggest to not execute `pip freeze` every time `get_installed_versions()` is called, as that is very slow.

**Comment by carmocca** [comment]
> if you really want to print those log messages with the version of those packages

I do, but in any case, an argument can be added to disable it

> decide the best approach to not rely on `requirements.txt`

If it's not found then return nothing

> I would also suggest to not execute `pip freeze` every time `get_installed_versions()` is called, as that is very slow.

Do you know any alternative? It is called only once at the beginning of scripts that do much slower things (like training or testing)

**Comment by carmocca** [comment]
Hi @lexming 

I have opened a PR with the fix previously mentioned, however, I haven't been able to reproduce:

> Folders laia/scripts and laia/models lack the needed __init__.py to be recognized as Python modules and, hence, they are ignored and not installed by pip.

I can import these without problems. Can you tell me about what is exactly failing? You can checkout the PR to try.
