### ISSUE TITLE
Looking for maintainers ?

### ISSUE THREAD

**Issue by starride-teklia** [jpuigcerver/PyLaia#43]
Hi, I'm a software engineer at Teklia, we are currently using PyLaia and planning to develop new features.
Would it be possible to be added as contributors so that we can publish patches and update/maintain the code a bit ? Thanks.
Solène

**Comment by jpuigcerver** [comment]
Hi Solène! Absolutely, we could add you as contributors. Who should I add?

@carmocca is the current maintainer of the project, please sync with to check if he has any changes comming.

**Comment by La0** [comment]
Hey @jpuigcerver , thanks for your reply. If you could add @starride-teklia & myself @La0 (I'm the CTO at @teklia) :+1:
