### ISSUE TITLE
Does PyLaia support line level or it can process complete form? 

### ISSUE THREAD

**Issue by Mohammed20201991** [jpuigcerver/PyLaia#66]
Thanks for great toolkit I am just wondering if we can use this tool kit for complete for detection (more than line text)?
if not please refer which tool or model can be used for text line segmentation ? to perform text generation for the next step ?

**Comment by starride-teklia** [comment]
Hi @Mohammed20201991!
PyLaia can only process text lines, so you need to extract lines first. I suggest you try a pre-trained line segmentation model on your documents:
* [tesseract](https://pypi.org/project/pytesseract/) (or any other OCR) for printed documents
* [doc-ufcn](https://pypi.org/project/doc-ufcn/) ([weights](https://huggingface.co/Teklia/doc-ufcn-generic-historical-line)) or [docExtractor](https://github.com/monniert/docExtractor) for handwritten/historical documents

If these are not satisfactory, you can fine-tune [Doc U-FCN](https://pypi.org/project/doc-ufcn/) on your documents.
